from flask import Flask, render_template, request, jsonify
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Initialize Flask app
app = Flask(__name__)
app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', 'your-secret-key-here')

# Import security modules
from modules.password_checker import check_password_strength
from modules.phishing_detector import detect_phishing
from modules.file_scanner import scan_file

# ==================== Routes ====================

@app.route('/')
def index():
    """Main page - displays the AI CyberShield interface"""
    return render_template('index.html')

@app.route('/api/check-password', methods=['POST'])
def api_check_password():
    """
    API endpoint for password strength analysis
    Expected JSON: {"password": "user_password"}
    Returns: {"score": int, "strength": str, "feedback": list, "percentage": float}
    """
    try:
        data = request.json
        password = data.get('password', '')
        
        if not password:
            return jsonify({'error': 'Password is required'}), 400
        
        result = check_password_strength(password)
        return jsonify(result), 200
    
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/check-phishing', methods=['POST'])
def api_check_phishing():
    """
    API endpoint for phishing URL detection
    Expected JSON: {"url": "https://example.com"}
    Returns: {"url": str, "risk_level": str, "risk_score": int, "indicators": list, "recommendation": str}
    """
    try:
        data = request.json
        url = data.get('url', '')
        
        if not url:
            return jsonify({'error': 'URL is required'}), 400
        
        result = detect_phishing(url)
        return jsonify(result), 200
    
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/scan-file', methods=['POST'])
def api_scan_file():
    """
    API endpoint for file threat analysis
    Expected JSON: {"file": "filename.exe"}
    Returns: {"filename": str, "extension": str, "threat_level": str, "risk_score": int, "indicators": list}
    """
    try:
        data = request.json
        filename = data.get('file', '')
        
        if not filename:
            return jsonify({'error': 'Filename is required'}), 400
        
        result = scan_file(filename)
        return jsonify(result), 200
    
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/security-tips', methods=['GET'])
def api_security_tips():
    """
    API endpoint for cybersecurity tips and best practices
    Returns: {"tips": [list of security tips]}
    """
    try:
        tips = {
            'tips': [
                '🔐 Use strong, unique passwords for each account',
                '🔑 Enable two-factor authentication (2FA) whenever possible',
                '🎣 Be cautious of suspicious emails and links from unknown senders',
                '🔄 Keep your software, OS, and applications updated regularly',
                '🛡️ Use a reliable antivirus/anti-malware solution',
                '💾 Regularly backup important data to secure locations',
                '🚫 Never share personal information online unless necessary',
                '📱 Use a password manager to store complex passwords securely',
                '🌐 Only use HTTPS websites (look for the padlock icon)',
                '⚠️ Verify sender identity before clicking email links',
                '🔓 Never leave devices unattended without locking them',
                '📧 Be skeptical of urgent requests for sensitive information',
                '🎯 Use a VPN on public WiFi networks',
                '🧠 Educate yourself about current cyber threats',
                '📞 Contact IT support if you suspect a security breach'
            ],
            'count': 15,
            'generated_at': 'AI CyberShield Platform',
            'version': '1.0.0'
        }
        return jsonify(tips), 200
    
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/generate-report', methods=['POST'])
def api_generate_report():
    """
    API endpoint for generating security reports
    Expected JSON: {"scan_data": {...}}
    Returns: {"report": {...}, "timestamp": str}
    """
    try:
        data = request.json
        
        report = {
            'overall_security_score': 75,
            'assessment_date': 'Generated by AI CyberShield',
            'components_analyzed': 3,
            'recommendations': [
                'Implement stronger password policies',
                'Educate users about phishing attacks',
                'Deploy file scanning tools',
                'Enable security monitoring'
            ],
            'next_steps': [
                'Review security policies',
                'Conduct security awareness training',
                'Implement recommended tools',
                'Monitor for threats'
            ]
        }
        return jsonify(report), 200
    
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# ==================== Error Handlers ====================

@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors"""
    return jsonify({'error': 'Resource not found'}), 404

@app.errorhandler(500)
def server_error(error):
    """Handle 500 errors"""
    return jsonify({'error': 'Internal server error'}), 500

# ==================== Main ====================

if __name__ == '__main__':
    # Create necessary directories
    os.makedirs('uploads', exist_ok=True)
    os.makedirs('logs', exist_ok=True)
    
    # Run Flask development server
    # For production, use a production server like Gunicorn
    app.run(
        debug=True,
        host='0.0.0.0',
        port=5000,
        threaded=True
      )
  
